import Head from 'next/head'
import { Inter } from 'next/font/google'
import { HomePage } from '@/components/home/home-page'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {

  console.log(data)
  return (
    <div>
      <Head>
        <title>Showcase App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main>
        
      <HomePage data={data}/>
        
        
      </main>


    </div>
  )
}

export async function getServerSideProps(){
  const {memory_categories} = await import("/data/data.json");

  return {
    props: {
      data: memory_categories
    }
  }
}
